export const image = [
  [
    "./images/33seater.png",
    "33 Seater Ashok Leyland  (2+2)",
    "Starting from:",
    "₹45/km ₹500/hr",
    "Ahmedabad",
    "Driver Bata ₹500/day",
    "Local Package Start From",
    "Updated Soon",
    "",
    "Fuel Included",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/charging_socket.svg",
    "Charging Point",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/music.svg",
    "Back Compartment Storage ",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/magazine_pouch.svg",
    "Music system & 2More",
    "Get Best Price",
  ],
  [
    "./images/ashok.png",
    "41 Seater Ashok Leyland  (2+2)",
    "Starting from:",
    "₹45/km ₹600/hr",
    "Ahmedabad",
    "Driver Bata ₹500/day",
    "Local Package Start From",
    "4Hours40Kms:",
    "₹8500",
    "Fuel Included",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/ic_legspace.svg",
    "Extra Leg Space",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/charging_socket.svg",
    "Charging Point",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/magazine_pouch.svg",
    "Back Compartment Storage&More",
    "Get Best Price",
  ],
  [
    "./images/Seater.png",
    "50 Seater Ashok Leyland  (2+2)",
    "Starting from:",
    "₹45/km ₹600/hr",
    "Ahmedabad",
    "Driver Bata ₹500/day",
    "Local Package Start From",
    "4Hours40Kms:",
    "₹8500",
    "Fuel Included",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/music.svg",
    "Music system",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/ic-fastag.svg",
    "FastTag",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/ic_legspace.svg",
    "Extra Leg Space& 9 More",
    "Get Best Price",
  ],
  [
    "./images/sleeper.png",
    "40 Sleeper Ashok Leyland(2+2)",
    "Starting from:",
    "₹62/km ₹600/hr",
    "Ahmedabad",
    "Driver Bata ₹400/day",
    "Local Package Price Willbe",
    "Updated Soon",
    "",
    "Fuel Included",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/charging_socket.svg",
    "Charging Point",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/magazine_pouch.svg",
    "Back Compartment Storage",
    "https://www.redbus.in/bushire/static/icons/amenitiesv2/music.svg",
    "Music system & 2More",
    "Get Best Price",
  ],
];
